---
- name: Converge
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: Bootstrapping Python
      ansible.builtin.raw: zypper install -y python3 python3-selinux
      changed_when: false

    - name: Gathering Facts
      ansible.builtin.setup:

  roles:
    - role: apptainer
