---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "opensuse/leap:${MOLECULE_DISTRO:-15.4}"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
