---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "opensuse/leap:${MOLECULE_DISTRO:-15.4}"
    dockerfile: Dockerfile.j2
    pre_build_image: false
    command: /usr/lib/systemd/systemd
    cgroupns_mode: host
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
